# fly.toml app configuration file generated for ausgridbot on 2024-02-02T22:38:23+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ausgridbot'
primary_region = 'syd'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[env]
  MASTODON_SERVER = 'https://howse.social'
  MASTODON_TOOT_INTERVAL = '1800'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
